apiVersion: v1
entries:
  gpu-operator:
  - apiVersion: v2
    appVersion: v1.7.0
    created: "2021-10-06T20:00:16.2749274+05:30"
    dependencies:
    - condition: nfd.enabled
      name: node-feature-discovery
      repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
      version: 0.8.2
    description: NVIDIA GPU Operator creates/configures/manages GPUs atop Kubernetes
    digest: 75d8bdb255ababbfa47b61d8de6256c611e672d1372bd5ec3e4aff8d96e92980
    home: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/overview.html
    icon: https://assets.nvidiagrid.net/ngc/logos/GPUoperator.png
    keywords:
    - gpu
    - cuda
    - compute
    - operator
    - deep learning
    - monitoring
    - tesla
    kubeVersion: '>= 1.16.0-0'
    name: gpu-operator
    sources:
    - https://github.com/NVIDIA/gpu-operator
    urls:
    - gpu-operator/gpu-operator-v1.7.0.tgz
    version: v1.7.0
generated: "2021-10-06T20:00:16.2657307+05:30"
